spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/unischedule
    username: root
    password: Hoanglam06112003@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
  # Enable spring data repos
  data:
    jpa:
      repositories:
        enabled: true


url:
  tuition: https://daotao.vnua.edu.vn/Default.aspx?page=xemhocphi&id=
  schedule: https://daotao.vnua.edu.vn/Default.aspx?page=thoikhoabieu&sta=1&id=
  test_schedule: https://daotao.vnua.edu.vn/Default.aspx?page=xemlichthi&id=
  score_semester: https://daotao.vnua.edu.vn/Default.aspx?page=xemdiemthi&id=
  home: https://daotao.vnua.edu.vn/Default.aspx
  university_news_link_all: https://daotao.vnua.edu.vn/default.aspx?page=danhsachthongtin&type=1
  all_semester: https://daotao.vnua.edu.vn/default.aspx?page=thoikhoabieu&load=all&sta=1&lang=y
  faculty_of_fisheries: https://khoathuysan.vnua.edu.vn
  faculty_of_it: https://fita.vnua.edu.vn/tin-tuc
logging:
  level:
    root: info
