spring:
  config:
    activate:
      on-profile: dev

url:
  tuition: https://daotao.vnua.edu.vn/Default.aspx?page=xemhocphi&id=
  schedule: https://daotao.vnua.edu.vn/Default.aspx?page=thoikhoabieu&sta=1&id=
  test_schedule: https://daotao.vnua.edu.vn/Default.aspx?page=xemlichthi&id=
  score_semester: https://daotao.vnua.edu.vn/Default.aspx?page=xemdiemthi&id=
  home: https://daotao.vnua.edu.vn/Default.aspx
  faculty_of_fisheries: https://khoathuysan.vnua.edu.vn
  university_news_link_all: https://daotao.vnua.edu.vn/default.aspx?page=danhsachthongtin&type=1
  all_semester: https://daotao.vnua.edu.vn/default.aspx?page=thoikhoabieu&load=all&sta=1&lang=y